### ISSUE TITLE
Bug with one-of

### ISSUE THREAD

**Issue by ystan-** [finos/symphony-wdk#123]
### Steps to Reproduce:
Setup 3 workflows that perform the same logic:
* Send a form
* Wait for form submission to update that message

```yaml
# Simple linear
id: abc
activities:
  - send-message:
      id: init
      on:
        message-received:
          content: abc
      content: |
        <form id="init"><button type="action" name="x">Init</button></form>
  - update-message:
      id: aloha
      on:
        form-replied:
          form-id: init
      message-id: ${init.outputs.msgId}
      content: Hey
```

```yaml
# Use one-of but with only 1 event
id: def
activities:
  - send-message:
      id: init
      on:
        message-received:
          content: def
      content: |
        <form id="init"><button type="action" name="x">Init</button></form>
  - update-message:
      id: aloha
      on:
        one-of:
        - form-replied:
            form-id: init
      message-id: ${init.outputs.msgId}
      content: Hey
```

```yaml
# Use one-of with 2 events
id: ghi
activities:
  - send-message:
      id: init
      on:
        message-received:
          content: ghi
      content: |
        <form id="init"><button type="action" name="x">Init</button></form>
  - update-message:
      id: aloha
      on:
        one-of:
        - form-replied:
            form-id: init
        - message-received:
            content: hey
      message-id: ${init.outputs.msgId}
      content: Hey
```

### Expected Result:
All 3 workflows should have identical logic

### Actual Result:
Without `one-of`, the workflow works as expected
![abc](https://user-images.githubusercontent.com/7151832/175465890-41bac1c8-f41c-4c8b-9c81-62efec744631.png)

Using a `one-of` with only 1 event, the workflow does not wait for the event and executes the next activity immediately after completion of the first.
![def](https://user-images.githubusercontent.com/7151832/175465919-a1ffef94-ccfe-427d-a095-382fa22de08b.png)

Using a `one-of` with 2 events, the workflow ignores the first event if it happens and only executes the next activity on the second event (sending a `hey` message)
![ghi](https://user-images.githubusercontent.com/7151832/175465929-16615eaf-e039-4089-9cc0-d1821868ad3b.png)

### Environment:
WDK 1.1.0
