### ISSUE TITLE
Unicode Support for execute-request

### ISSUE THREAD

**Issue by ystxn** [finos/symphony-wdk#124]
## Bug Report
WDK's `execute-request` is not unicode compatible and transforms unicode characters to question marks in the `outputs` object returned.

### Steps to Reproduce:
```yaml
id: post
activities:
  - execute-request:
      id: init
      on:
        message-received:
          content: post
      method: POST
      url: https://httpbin.org/post
      headers:
        Content-Type: multipart/form-data
      body:
        text: Hello こんにちは世界

  - execute-script:
      id: debug
      script: println init.outputs

  - send-message:
      id: sendResponse
      content: ${init.outputs.body.form.text}
```

### Expected Result:
1. Console will print the original text: `Hello こんにちは世界`
2. Bot will send original text: `Hello こんにちは世界`

### Actual Result:
1. Console prints: `Hello ???????`
2. Bot sends: `Hello ???????`

### Environment:
WDK 1.1.0
