### ISSUE TITLE
Support Inline Templates

### ISSUE THREAD

**Issue by ystxn** [finos/symphony-wdk#172]
### Description of Problem:
The `send-message` activity currently supports the `content` payload being either a MessageML string or a sub-field named `template` that expects an external file reference. Using `template` will load the file using the freemarker templating engine and process it using global and event variables. Using just the `content` field does not pass the payload into the templating engine, so including any freemarker syntax will throw errors.

### Potential Solutions:
- Option 1: Re-use the `template` field for inline content. If the template field does not resolve to a file, try loading it as template content instead.
```yaml
- send-message:
    id: example
    content:
      template: <#list variables.collection as document>${document}</#list>
```

- Option 2: Introduce a new field under content that is mean to contain inline template content
```yaml
- send-message:
    id: example
    content:
      template-inline: <#list variables.collection as document>${document}</#list>
```

- Option 3: Rename the current file loader to `template-file`
```yaml
- send-message:
    id: example1
    content:
      template-file: templates/documents.ftl

- send-message:
    id: example2
    content:
      template: <#list variables.collection as document>${document}</#list>
```
