### ISSUE TITLE
Standard Debug Activity

### ISSUE THREAD

**Issue by ystxn** [finos/symphony-wdk#197]
### Description of Problem:
* The structure and contents of objects (event, variable, or output) are opaque when writing workflows with WDK
* Workflow developers often have to write a manual "debug" script to print out an object to inspect it
* Example of a debug script:
```yaml
- execute-script:
    id: debug
    script: |
        import groovy.json.JsonOutput
        println JsonOutput.prettyPrint(JsonOutput.toJson(my_object))
```

### Potential Solutions:
Introduce a standard debug activity that does the above. The activity output should be filled with the same object so that it can also be inspected by the monitoring endpoints.
Example:
```yaml
- debug:
    id: debug
    object: my_object
```
