### ISSUE TITLE
Support external message template

### ISSUE THREAD

**Issue by symphony-soufiane** [finos/symphony-wdk#26]
Right now when sending a message from a workflow, its content is part of the SWADL file.
It would be interesting to be able to reference an external file (that can in the ./workflows folder). This way complex messages can be decoupled from SWADL making it easier to read.

So in the send-message activity, we could have a content.template attribute.

```
send-message:
  content: BlahBlah
  content:
    template: ./myMessage.mml.xml
```
