### ISSUE TITLE
Support event filtering

### ISSUE THREAD

**Issue by symphony-soufiane** [finos/symphony-wdk#27]
Right now, when a workflow activity is set to be triggered on UserJoinedRoom for example, no matter the user who triggered the event (by joining the room for instance), the activity will be executed. The same thing happens with the other different Datafeed events. 
We would like to filter events so we can, for instance, only react to UserJoinedRoom triggered by a specific user, not any one.

**Comment by ystxn** [comment]
Event filtering works after #130 #131 #132

```yaml
- send-message:
    id: init
    on:
      message-received:
        content: /xyz
    if: ${event.source.message.stream.streamId == 'PHJSEjnOmVsqrf8ZMX8CBn___nqoBLzXdA'}
    content: Hi
```
