### ISSUE TITLE
Support of message update

### ISSUE THREAD

**Issue by symphony-soufiane** [finos/symphony-wdk#45]
### Description of Problem:
We want to be able to update message content
Do we use send-message activity with an optional property (messageId) or do we create a simple dedicated activity?

If we want an activity oriented SWADL, the first option is convenient. If we want to be close to Symphony public api, then the second one is better.

### SWADL suggestion
```

update-message:
      id: updateMessageId
      messageId: MSG_ID
      content:  NEW MSG CONTENT
```

or

```
send-message:
   id: updateMessageId
   messageId: MSG_ID        // If set, then the message is updated. otherwise, a new message is sent like the activity works today
   content: NEW MSG CONTENT
```
