### ISSUE TITLE
Allow variable usage of variables in list users-id

### ISSUE THREAD

**Issue by symphony-youri** [finos/symphony-wdk#61]
user-ids parameter requires a list of Number-based ids if we try to use ${...} the ids are passed as String and the workflow fails. We should allow the usage of variables in this field.

Example of workflow: 

```
- send-message:
  id: informationAnalysis
  on:
    form-replied:
      form-id: requestApprover
  to:
    user-ids:
      - ${event.initiator.user.userId}
  content: |
    Please review the following Information Analysis
```
